### ISSUE TITLE
Field User: Authenticate to begin using application

### ISSUE THREAD

**Issue by xagronaut** [WorldVax/FC-Connect#74]
AS A Field User
I WANT TO provide my credentials
SO THAT I may be granted access to application functions to which I have permission.

### Implementation Tasks
- [ ] Design login view (this should include username and password, with a Submit button).
- [ ] Replace default splash screen view (use existing one for first-time experience) with a modified version that includes the login functionality. If no users are registered in storage, use the full splash screen (with a "Get Started" button added which will transfer you to the login view).  Some of the look and feel should be preserved, specifically some form of the logo and a brief description, but the importance should be placed on the login interface. An "About" button can be added to the navigation.

The following screen should be kept with the addition of the "Get Started" button.
<img src="https://cloud.githubusercontent.com/assets/1373511/19974956/a74fbb12-a1c0-11e6-83cb-d686bea54d9b.png" width="400" />

The view can be modified to dynamically swap the text reading, "On average, one child dies every 21 seconds...track immunizations with FC-Connect." when the "Get Started" button is tapped.

- [ ] Record a login attempts, successful and failed, to the Logging Service (See Issue https://github.com/WorldVax/FC-Connect/issues/68 for details on the Logging Service). User's identity should be recorded for a successful login, and the attempted login name should be recorded for failed attempts, but no recording of the password used should occur.
- [ ] Add a "Log out" selection to the navigation that will trigger the Security Service to invalidate the user's session after logging the logout event (See Issue https://github.com/WorldVax/FC-Connect/issues/68 for details on the Logging Service). User's identity should be recorded.
- [ ] Design Security Service (Issue #75); it can be "stubbed" for now with local data, but a secure means of encrypting credentials or verifying them on an external endpoint will be done in the future).

### Acceptance Criteria
- [ ] User access the application for the first time.
- [ ] The introductory splash screen is presented with full descriptive intro and a "Get Started" button.
- [ ] All navigation elements that require an authenticated user should be hidden, disabled, or otherwise inaccessible. This includes the FAB (Floating Action Button) for search depicted on the screenshot.
- [ ] The User presses "Get Started" and the descriptive intro and "Get Started" button are replaced with the login controls.
- [ ] The User enters username and password incorrectly, and a message is displayed indicating the failure.
- [ ] The application logs the failure using the appropriate event type using the Logging Service.
- [ ] The User enters username and password correctly, and the login controls are replaced by a display of the logged in user's username on the splash screen.
- [ ] Navigation elements previously hidden or disabled become available for selection and activation. This includes the FAB (Floating Action Button) for search depicted on the screenshot.
